
/**
Constructor
Do not call Function in Constructor.
*/
class edit_post()
{
	super();

	//TODO:edit here

}
extends AView;


function edit_post*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function edit_post*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function edit_post*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
